dependencies = [
    'jinja2',
    'matplotlib',
    'numpy<2.3',
    'ordered-set',
    'py-cpuinfo',
    'tqdm',
    'typing_extensions',
    'pyyaml',
    'scikit-learn',
    'xdsl~=0.57.1',
    'strictyaml',
    'tomlkit',
]

[groups.default]
include = ["mlir", "tvm"]

[groups.dev]
include = ["default", "test"]

[groups.test]
dependencies = [
    "coverage>=7.8.0",
    "filecheck==1.0.3",
    "lit",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings-python",
    "mypy==2.3.1",
    "pytest",
    "pytest-xdist",
    "pyright==1.1.414",
    "types-PyYAML",
    "marimo==0.19.6",
    "ruff==0.14.10",
]

[groups.llvm]
publish = false
dependencies = [
    'xtc-llvm-tools==22.1.8.2',
]

[groups.mlir]
include = ["llvm"]
dependencies = [
    'xtc-mlir-tools==22.1.8.3',
    'xtc-mlir-python-bindings==22.1.8.3',
    'xtc-mlir-extra-tools==22.1.8.7',
]

[groups.tvm]
dependencies = [
    'apache-tvm==0.26.0',
    'apache-tvm-ffi==0.1.13.post3',
]
