#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024-2026 The XTC Project Authors
#
from abc import ABC, abstractmethod

import xtc.itf


class Executor(ABC):
    """An abstract implementation of a Module executor.

    An Executor is responsible for running compiled Modules and validating their
    execution. It provides the runtime environment for executing the compiled code,
    typically in the form of shared objects generated by the compilation process.
    """

    @abstractmethod
    def execute(self) -> int:
        """Executes the associated Module.

        Runs the compiled code contained in the Module, providing the necessary
        runtime environment and handling any required setup/teardown.

        Returns:
            Status code indicating execution success (0) or failure (non-zero)
        """
        ...

    @property
    @abstractmethod
    def module(self) -> "xtc.itf.comp.Module":
        """Returns the Module being executed.

        Returns:
            The compiled Module this executor is responsible for running
        """
        ...
