name: XTC Build and Tests

# Runs on pushes targeting the main branch, pull request and manual Actions tab
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, macos-15]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps: &build-steps
      - name: Checkout XTC Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Ensure PR has linear history
        if: github.event_name == 'pull_request'
        run: |
          MERGE_COMMITS="$(git rev-list --merges "${GITHUB_SHA}"^1.."${GITHUB_SHA}"^2)"
          if [ -n "${MERGE_COMMITS}" ]; then
            echo "::error::PR contains merges, always use rebase for updating branches: Merge commits: ${MERGE_COMMITS}" >&2
            exit 1
          fi
      - name: Install Linux Packages
        if: runner.os == 'Linux'
        # Note: package cache with awalsh128/cache-apt-pkgs-action does not work correctly, use standard install.
        run: |
          sudo apt install -y build-essential libomp5 binutils-aarch64-linux-gnu binutils-x86-64-linux-gnu libpfm4-dev
      - name: Install macOS Packages
        if: runner.os == 'macOs'
        run: |
          brew install libomp x86_64-linux-gnu-binutils aarch64-elf-binutils
          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:${DYLD_LIBRARY_PATH}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install XTC Package in dev mode
        run: |
          pip install -e .[dev]
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          pip install -r mlir_requirements.txt
          pip install -r tvm_requirements.txt
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          pip install -r macos_mlir_requirements.txt
          pip install -r macos_tvm_requirements.txt
      - name: Dump Environment information
        run: |
          python -c 'import sys; print(sys.version)'
          pip list
          env | sort
      - name: Run Checks
        run: |
          COV=scripts/coverage/coverage_run.sh
          $COV make check
      - name: Run Explore One Shot
        run: |
          COV=scripts/coverage/coverage_run.sh
          env STRATEGIES=tile8dvr BACKENDS="tvm mlir" $COV ./scripts/explore/run-explore-one-shot.sh artifacts/explore
      - name: Run Explore Variants
        run: |
          COV=scripts/coverage/coverage_run.sh
          env STRATEGIES=tile8dvr BACKENDS="tvm mlir" $COV ./scripts/explore/run-explore-variants.sh artifacts/explore
          env NOSHOW=1 scripts/explore/display-explore-variants.sh artifacts/explore
      - name: Generate Coverage Reports
        run: |
          coverage combine >/dev/null
          coverage report
          mkdir -p artifacts/coverage
          coverage xml -o artifacts/coverage/coverage.xml
          coverage report --format=markdown >artifacts/coverage/coverage.md
          coverage html -d artifacts/coverage/html
      - name: Publish artifacts
        if: matrix.python-version == '3.12'
        uses: actions/upload-artifact@v5
        with:
          name: artifacts-os-${{ matrix.os }}
          path: artifacts/
      - name: Publish Coverage
        if: matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          files: artifacts/coverage/coverage.xml
          flags: py${{ matrix.python-version }}-${{ matrix.os }}
          name: py${{ matrix.python-version }}-${{ matrix.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  pr-build:
    if: github.event_name == 'pull_request'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15]
        python-version: ["3.12"]
    steps: *build-steps
